# Generated by Django 2.0.13 on 2019-03-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64)),
                ('year_of_birth', models.IntegerField()),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ('second_name', 'first_name'),
            },
        ),
    ]
